apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - name: {{ .Values.name }}-svc
    port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: {{ .Values.name }}
  type: ClusterIP
  clusterIP: None